apiVersion: backstage.io/v1alpha1
kind: User

metadata:
  name: ranjeet

spec:
  profile:
    displayName: Ranjeet Kumar
    email: rkpranjeet198@gmail.com

  memberOf:
    - platform-team