version: "3.9"

services:
  backstage:
    image: backstage-node22:latest
    container_name: backstage
    ports:
      - "3000:3000"
      - "7007:7007"
    environment:
      - HOST=0.0.0.0
    volumes:
      - ./packages/backend/backstage-data:/app/packages/backend/backstage-data